site_name: Market+
site_description: 
site_author: Charl_iey
site_url: https://charliey2.github.io/market-plus

repo_name: charliey2/market-plus
repo_url: https://github.com/charliey/market-plus
edit_uri: ""

docs_dir: docs
site_dir: site

theme:
  logo: https://user-images.githubusercontent.com/51117782/104590568-71724f80-5663-11eb-9bc1-344fc2a4193c.png
  favicon: https://user-images.githubusercontent.com/51117782/113474423-cefa8900-9467-11eb-8678-d69cbb0b3966.png
  name: material
  features:
    - navigation.tabs
    #- navigation.instant
    #- navigation.sections
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - lua

extra_javascript:
  - javascripts/tags.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/charliey2/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Charl_iey
    - icon: fontawesome/brands/discord
      link: https://discord.gg/
    - icon: fontawesome/solid/link
      link: https://iriscore.dev

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences

nav:
  - Home:
    - Introduction: index.md