site_name: irisCORE
site_description: 
site_author: Charl_iey
site_url: https://surnautica.github.io/iriscore

docs_dir: docs

site_dir: docs_build

theme:
  logo: https://github.com/charliey2/project-assets/blob/main/irisCORE/logo.png?raw=true
  favicon: https://github.com/charliey2/project-assets/blob/main/irisCORE/logo.png?raw=true
  name: material
  features:
    - navigation.tabs
    #- navigation.instant
    #- navigation.sections
  font:
    text: Rubik
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - lua

extra_javascript:
  - javascripts/tags.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/charliey2/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Charl_iey
    - icon: fontawesome/brands/discord
      link: https://discord.gg/
    - icon: fontawesome/solid/link
      link: https://iriscore.dev
  generator: false

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Site 23:
    - Developer:
      - Server API: site23/developer/server-api
      - Client API: site23/developer/client-api
      - Shared API:
        - Utility: site23/developer/shared-api/utility.md
    - CC BY-SA 3.0: site23/licence.md
  - Home:
    - Introduction: index.md
    - Installation: home/install.md
    - Examples: home/examples.md
  - API:
    - Methods: api/methods.md
    - Events: api/events.md