site_name: Site 23
site_description: 
site_author: Charl_iey
site_url: https://site23.xyz

docs_dir: docs

site_dir: docs_build

copyright: >
  Copyright &copy; 2023 irisCORE —
  <a href="https://surnautica.github.io/iriscore/terms">Terms</a> —
  <a href="https://surnautica.github.io/iriscore/privacy">Privacy</a> —
  <a href="#__consent">Cookies</a>

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - navigation.instant
    #- toc.integrate
  font:
    text: Rubik
  palette:
    scheme: slate
    primary: black
    accent: blue
  favicon: site/favicon.png
  logo: site/favicon.png
  highlightjs: true
  hljs_languages:
    - lua

extra_javascript:
  - site/javascripts/tags.js

extra_css:
  - site/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Charl_iey
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_TOKEN
  consent:
    title: We use cookies to make your experience better
    description: >-
      Site 23 uses cookies to save your preferences, feedback, and measure site statistics. You're always in control of your data. <a href="https://surnautica.github.io/iriscore/privacy"><i>Privacy</i></a>

plugins:
  - search
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: false

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - footnotes
  - md_in_html