site_name: Market+
site_description: 
site_author: Charl_iey
site_url: https://charliey2.github.io/market-plus

repo_name: charliey2/market-plus
repo_url: https://github.com/charliey2/market-plus
edit_uri: ""

docs_dir: docs

site_dir: docs_build

theme:
  logo: docs/assets/logo.png
  favicon: docs/assets/logo.png
  name: material
  features:
    - navigation.tabs
    #- navigation.instant
    #- navigation.sections
  font:
    text: Rubik
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - lua

extra_javascript:
  - javascripts/tags.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/charliey2/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Charl_iey
    - icon: fontawesome/brands/discord
      link: https://discord.gg/
    - icon: fontawesome/solid/link
      link: https://iriscore.dev

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home:
    - Introduction: index.md
    - API:
      - Methods: api/methods.md
      - Events: api/events.md