site_name: irisCORE
site_description: 
site_author: Charl_iey
site_url: https://surnautica.github.io/iriscore

docs_dir: docs

site_dir: docs_build

theme:
  logo: https://github.com/charliey2/project-assets/blob/main/irisCORE/logo.png?raw=true
  favicon: https://github.com/charliey2/project-assets/blob/main/irisCORE/logo.png?raw=true
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - navigation.instant
    #- navigation.sections
  font:
    text: Rubik
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - lua

extra_javascript:
  - javascripts/tags.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SurNautica/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Charl_iey
  generator: false

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list

nav:
  - Group:
    - group/index.md
    - Our Team: group/team.md
  - Site 23:
    - site23/index.md
    - Developer:
      - site23/developer/index.md
      - Server API:
        - site23/developer/server-api/index.md
        - Interactions: site23/developer/server-api/interaction.md
      - Client API:
        - site23/developer/client-api/index.md
        - Interface: site23/developer/client-api/interface.md
      - Shared API:
        - site23/developer/shared-api/index.md
        - Utility: site23/developer/shared-api/utility.md
        - Network: site23/developer/shared-api/network.md
    - Cerberus: site23/cerberus/index.md
    - Acknowledgements: site23/acknowledgements.md
    - License: site23/license.md