site_name: Site 23
site_description: 
site_author: Charl_iey
site_url: https://community.site23.xyz

docs_dir: docs

site_dir: docs_build

theme:
  logo: https://github.com/charliey2/project-assets/blob/main/irisCORE/logo.png?raw=true
  favicon: https://github.com/charliey2/project-assets/blob/main/irisCORE/logo.png?raw=true
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - navigation.instant
    #- navigation.sections
  font:
    text: Rubik
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
  highlightjs: true
  hljs_languages:
    - lua

extra_javascript:
  - javascripts/tags.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SurNautica/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Charl_iey
  generator: false

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list

nav:
  - Departments:
    - Civil:
      - Scientific Department:
        - departments/civil/scd/index.md
        - poopy: departments/civil/scd/index2.md
      - Internal Security Service:
        - departments/civil/iss/index.md