site_name: Site 23
site_description: 
site_author: Charl_iey
site_url: https://site23.xyz

docs_dir: docs

site_dir: docs_build

copyright: >
  Copyright &copy; 2023 irisCORE —
  <a href="https://surnautica.github.io/iriscore/terms">Terms</a> —
  <a href="https://surnautica.github.io/iriscore/privacy">Privacy</a> —
  <a href="#__consent">Cookies</a>

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - navigation.instant
  font:
    text: Rubik
  palette:
    scheme: slate
    primary: black
    accent: blue
  favicon: assets/favicon.png
  logo: assets/favicon.png
  highlightjs: true
  hljs_languages:
    - lua

extra_javascript:
  - assets/javascripts/tags.js

extra_css:
  - assets/stylesheets/extra.css

extra:
  social:
    - icon: iriscore/logo
      link: https://github.com/SurNautica/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Charl_iey
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_TOKEN
  consent:
    title: We use cookies to make your experience better
    description: >-
      Site 23 uses cookies to save your preferences, feedback, and measure site statistics. You're always in control of your data. <a href="https://surnautica.github.io/iriscore/privacy"><i>Privacy</i></a>

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - footnotes

nav:
  - Departments:
    - Civil:
      - Scientific Department:
        - departments/civil/scd/index.md
      - Internal Security Service:
        - departments/civil/iss/index.md
      - Engineering and Technical Service:
        - departments/civil/ets/index.md
        - Atomic Operations: departments/civil/ets/atindex.md
    - Combative:
      - Security Department:
        - departments/combat/sd/index.md
        - Asset Containment Unit: departments/combat/sd/asuindex.md
        - Emergency Response Unit: departments/combat/sd/eruindex.md