name: MkDocs Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material
          pip install pymdown-extensions
      - name: Build site
        run: mkdocs build -d .
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MAIN_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages